import React from "react"
import AppBar from "../../components/AppBar";
import { FaArrowLeft } from "react-icons/fa";
import { appname } from "../../utils/constants";


export const metadata = {
  title: "Privacy Policy | " + appname,
};

function page() {
    return (
        <>
            <AppBar leadingIcon={<FaArrowLeft className="h-5 w-5" />} title="Privacy Policy" ></AppBar>

            <div className="pt-16 pl-8 pr-8">
                <br></br>
                <b >1. INTRODUCTION</b><br></br>
                On behalf of (us, we, AIDFAST which also includes its affiliates) is the author and publisher of the internet resource www.aidfastbd.com (Website) on the world wide web and mobile applications (Mobile Applications) AIDFAST and AIDFAST for Providers. This privacy policy (Privacy Policy) explains how we collect, use, share, disclose and protect personal information about the End-User(s)/User(s)/Provider(s)/Practioner(s) as (defined in Agreement) as (You, Your(s)). We created this Privacy Policy to demonstrate our commitment to the protection of your privacy and your personal information. Your use of and access to the services are subject to this Privacy Policy.
                <br></br>
                BY USING THE SERVICES OR BY OTHERWISE GIVING US YOUR INFORMATION, YOU WILL BE DEEMED TO HAVE READ, UNDERSTOOD AND AGREED TO THE PRACTICES AND POLICIES OUTLINED IN THIS PRIVACY POLICY AND AGREE TO BE BOUND BY THE PRIVACY POLICY. YOU HEREBY CONSENT TO OUR COLLECTION, USE, SHARING, AND DISCLOSURE OF YOUR INFORMATION AS DESCRIBED IN THIS PRIVACY POLICY WE RESERVE THE RIGHT TO CHANGE, MODIFY, ADD OR DELETE PORTIONS OF THE TERMS OF THIS PRIVACY POLICY, AT OUR SOLE DISCRETION, AT ANY TIME. IF YOU DO NOT AGREE WITH THIS PRIVACY POLICY AT ANY TIME, DO NOT USE ANY OF THE SERVICES OR GIVE US ANY OF YOUR INFORMATION. IF YOU USE THE SERVICES ON BEHALF OF SOMEONE ELSE (SUCH AS YOUR CHILD) OR AN ENTITY (SUCH AS YOUR EMPLOYER), YOU REPRESENT THAT YOU ARE AUTHORISED BY SUCH INDIVIDUAL OR ENTITY TO (I) ACCEPT THIS PRIVACY POLICY ON SUCH INDIVIDUALS OR ENTITYS BEHALF, AND (II) CONSENT ON BEHALF OF SUCH INDIVIDUAL OR ENTITY TO OUR COLLECTION, USE, AND DISCLOSURE OF SUCH INDIVIDUALS OR ENTITYS INFORMATION AS DESCRIBED IN THIS PRIVACY POLICY.
                <br></br>
                This Privacy Policy states the following: The type of information collected from the Users, including Personal Information (as defined in the paragraph below) and Sensitive Personal Data or Information (as defined in paragraph below) relating to an individual;The purpose, means, and modes of collection, usage, processing, retention, and destruction of such information; and How and to whom AIDFAST will disclose such information?
                <br></br>
                <b>2. COLLECTION OF PERSONAL INFORMATION</b>
                Generally, some of the services require us to know who you are so that we can best meet your needs. When you access the services, or through any interaction with us via emails, telephone calls, or other correspondence, we may ask you to voluntarily provide us with certain information that personally identifies you or could be used to personally identify you. You hereby consent to the collection of such information by AIDFAST. Without prejudice to the generality of the above, information collected by us from you may include (but is not limited to) the following:
                <br></br>
                contact data (such as your email address and phone number); demographic data (such as your gender, your date of birth); data regarding your usage of the services and history of the appointments made by or with you through the use of services; other information that you voluntarily choose to provide to us such as information shared by you with us through emails or letters. The information collected from you by AIDFAST may constitute personal information or sensitive personal data or information. Personal Information is defined to mean any information that relates to a natural person, which, either directly or indirectly, in combination with other information available or likely to be available to a body corporate, is capable of identifying such person. Sensitive Personal Data or Information of a person means personal information about that person relating to: passwords; financial information such as bank accounts, credit, and debit card details, or other payment instrument details; physical, physiological, and mental health condition; sexual orientation; medical records and history; biometric information; visitor details as provided at the time of registration or thereafter; and call data records. AIDFAST will be free to use, collect and disclose information that is freely available in the public domain without your consent.
                <br></br>
                <b>3. PRIVACY STATEMENTS</b>
                <br></br>
                3.1 ALL USERS NOTE:
                This section applies to all Users.
                <br></br>
                3.1.1 Accordingly, a condition of each Users use of and access to the services is their acceptance of this Privacy Policy. Any User that does not agree with any provisions of the same has the option to discontinue the services provided by AIDFAST immediately.
                <br></br>
                3.1.2 All the information provided to AIDFAST by a User, including Personal Information or any Sensitive Personal Data or Information, is voluntary. You understand that AIDFAST may use certain information of yours, which has been designated as Personal Information or Sensitive Personal Data or Information, (a) to provide you the services, (b) for commercial purposes and in an aggregated or non-personally identifiable form for research, statistical analysis, and business intelligence purposes, (c) for sale or transfer of such research, statistical or intelligence data in an aggregated or non-personally identifiable form to third parties and affiliates (d) for communication purposes to provide You a better way of booking appointments and for obtaining feedback in relation to the Practitioners/Providers and their practice, (e) debugging customer support-related issues. (f) for the purpose of contacting you to complete any transaction if you do not complete a transaction after having provided us with your contact information in the course of completing such steps that are designed for completion of the transaction. AIDFAST also reserves the right to use the information provided by or about the End-User for the following purposes: Publishing such information on the Website/Mobile Applications. Contacting End-Users for offering new products or services. Contacting End-Users for taking product and Service feedback. Analyzing software usage patterns for improving product design and utility. Analyzing anonymized practice information for commercial use. Processing payment instructions including those through independent third-party service providers such as payment gateways, banking, and financial institutions for processing payment transactions or deferral of payment facilities. If you have voluntarily provided your Personal Information to AIDFAST for any of the purposes stated above, you hereby consent to such collection and use of such information by AIDFAST.
                <br></br>
                3.1.3 Collection, use, and disclosure of information that has been designated as Personal Information or Sensitive Personal Data or Information require your express consent. By affirming your assent to this Privacy Policy, you provide your consent to such use, collection, and disclosure as required under applicable law.
                <br></br>
                3.1.4 AIDFAST does not control or endorse the content, messages, or information found in any services and, therefore, AIDFAST specifically disclaims any liability with regard to the services and any actions resulting from your participation in any services, and you agree that you waive any claims against AIDFAST relating to the same.
                <br></br>
                3.1.5 You are responsible for maintaining the accuracy of the information you submit to us, such as your contact information provided as part of account registration. If your personal information changes, you may correct, delete inaccuracies, or amend information by making the change yourself or by contacting us through contact@aidfastbd.com. We will make good faith efforts to make requested changes in our then active databases as soon as reasonably practicable. If you provide any information that is untrue, inaccurate, out of date, or incomplete (or becomes untrue, inaccurate, out of date, or incomplete), or AIDFAST has reasonable grounds to suspect that the information provided by you is untrue, inaccurate, out of date, or incomplete, AIDFAST may, at its s ole discretion, discontinue the provision of the services to you.
                <br></br>
                3.1.6 If you wish to cancel your account or request that we no longer use your information to provide you with services, contact us at contact@aidfastbd.com. We will retain your information for as long as your account with the services is active and as needed to provide you with the services. We shall not retain such information for longer than is required for the purposes for which the information may lawfully be used or is otherwise required under any other law for the time being in force. After a period of time, your data may be anonymized and aggregated, and then may be held by us as long as necessary for us to provide our services effectively, but our use of the anonymized data will be solely for analytic purposes. Please note that your withdrawal of consent or cancellation of account may result in AIDFAST being unable to provide you with its services or to terminate any existing relationship AIDFAST may have with you.
                <br></br>
                3.1.7 If you wish to opt out of receiving non-essential communications such as promotional and marketing-related information regarding the services, please send us an email at contact@aidfastbd.com.
                <br></br>
                3.1.8 AIDFAST may require the User to pay with a credit card, wire transfer, debit card, or cheque for services for which subscription amount(s) is/are payable. AIDFAST will collect such Users credit card number and/or other financial institution information such as bank account numbers and will use that information for the billing and payment processes, including but not limited to the use and disclosure of such credit card numbers and information to third parties as necessary to complete such billing operation. Verification of credit information, however, is accomplished solely by the User through the authentication process. Users credit-card/debit card details are transacted upon secure sites of approved payment gateways which are digitally under encryption, thereby providing the highest possible degree of care as per current technology. However, the User is advised, however, that internet technology is not full proof safe and the User should exercise discretion on using the same.
                <br></br>
                3.1.9 Due to the communications standards on the Internet, when a User or the End-User or anyone who visits the Website/Mobile Applications, AIDFAST automatically receives the URL of the site from which anyone visits. AIDFAST also receives the Internet Protocol (IP) address of each Users computer (or the proxy server a User used to access the World Wide Web), The users computer operating system and type of web browser the User is using, email patterns, as well as the name of the Users ISP. This information is used to analyze overall trends to help AIDFAST improve its service. The linkage between the Users IP address and the Users personally identifiable information is not shared with or disclosed to third parties. Notwithstanding the above, AIDFAST may share and/or disclose some of the aggregate findings (not the specific data) in anonymized form (i.e., non-personally identifiable) with advertisers, sponsors, investors, strategic partners, and others in order to help grow its business.
                <br></br>
                3.1.10 The Website/Mobile Applications use temporary cookies to store certain (that are not sensitive personal data or information) that are used by AIDFAST and its service providers for the technical administration of the Website/Mobile Applications, research and development, and User administration. In the course of serving advertisements or optimizing services to its Users, AIDFAST may allow authorized third parties to place or recognize a unique cookie on the Users browser. The cookies, however, do not store any personal information of the User. You may adjust your internet browser to disable cookies. If cookies are disabled you may still use the Website/Mobile Applications, but the Website/Mobile Applications may be limited in the use of some of the features.
                <br></br>
                3.1.11 A User may have limited access to the Website/Mobile Applications without creating an account on the Website/Mobile Applications. In order to have access to all the features and benefits on our Website/Mobile Applications, a User must first create an account on our Website/Mobile applications. To create an account, a User is required to provide the following information, which such User recognizes and expressly acknowledges is personal information allowing others, including AIDFAST, to identify the User: Name, User ID, email address, country, age, mobile number, password chosen by the User, and valid financial account information. Other information requested on the registration page, including the ability to receive promotional offers from AIDFAST, is optional. AIDFASTmay, in the future, include other optional requests for information from the User to help AIDFAST to customize the Website/Mobile Applications to deliver personalized information to the User.
                <br></br>
                3.1.12 AIDFAST does not exercise control over the sites displayed as search results or links from within its services. These other sites may place their own cookies or other files on the Users computer, collect data or solicit personal information from the User, for which AIDFAST is not responsible or liable. Accordingly, AIDFAST does not make any representations concerning the privacy practices or policies of such third parties or terms of use of such websites, nor does AIDFAST guarantee the accuracy, integrity, or quality of the information, data, text, software, sound, photographs, graphics, videos, messages or other materials available on such websites. The inclusion or exclusion does not imply any endorsement by AIDFAST of the website, the websites provider, or the information on the website. If you decide to visit a third-party website linked to the Website/Mobile Applications, you do this entirely at your own risk. AIDFAST encourages the User to read the privacy policies of that website.
                <br></br>
                3.1.13 The Website/Mobile Applications may enable the User to communicate with other Users or to post information to be accessed by others, whereupon other Users may collect such data. Such Users are not authorized AIDFAST representatives or agents, and their opinions or statements do not necessarily reflect those of AIDFAST , and they are not authorized to bind AIDFAST to any contract. AIDFAST hereby expressly disclaims any liability for any reliance or misuse of such information that is made available by Users or visitors in such a manner.
                <br></br>
                3.1.14 AIDFAST maintains a strict No-Spam policy, which means that AIDFAST does not intend to sell, rent, or otherwise give your e-mail address to a third party without your consent.
                <br></br>
                3.1.15 AIDFAST has implemented the best international market practices and security policies, rules, and technical measures to protect the personal data that it has under its control from unauthorized access, improper use or disclosure, unauthorized modification, and unlawful destruction or accidental loss. However, for any data loss or theft due to unauthorized access to the Users electronic devices through which the User avails the services, AIDFAST shall not be held liable for any loss whatsoever incurred by the User.
                <br></br>
                3.1.16 AIDFAST implements reasonable security practices and procedures.
                <br></br>
                3.1.17 AIDFAST takes your right to privacy very seriously and other than as specifically stated in this Privacy Policy, will only disclose your personal information in the event it is required to do so by law, rule, regulation, law enforcement agency, governmental official, legal authority, or similar requirements or when AIDFAST, in its sole discretion, deems it necessary in order to protect its rights or the rights of others, to prevent harm to persons or property, to fight fraud and credit risk, or to enforce or apply the Privacy Policy.
                <br></br>
                3.2 PRACTITIONERS NOTE:
                This section applies to all Practitioners/Providers.
                <br></br>
                3.2.1 As part of the registration in the Website/Mobile Applications for Practitioners/Providers, certain information, including Personal Information or Sensitive Personal Data or Information is collected from the Practitioners/Providers.
                <br></br>
                3.2.2 All the statements in this Privacy Policy apply to all Practitioners/Providers, and all Practitioners/Providers are therefore required to read and understand the privacy statements set out herein prior to submitting any Personal Information or Sensitive Personal Data or Information to AIDFAST, failing which they are required to leave the services, including the Website/Mobile Applications immediately.
                <br></br>
                3.2.3 Practitioners/Providers personally identifiable information, which they choose to provide to AIDFAST, is used to help the Practitioners/Providers describe and identify themselves. This information is exclusively owned by AIDFAST. You will be the owner of your information and you consent to AIDFAST collecting, using, processing, and/or disclosing this information for the purposes hereinafter stated. AIDFAST may use such information for commercial purposes and in an aggregated or non-personally identifiable form for research, statistical analysis, and business intelligence purposes, and may sell or otherwise transfer such research, statistical, or intelligence data in an aggregated or non-personally identifiable form to third parties and affiliates. AIDFAST also reserves the right to use the information provided by or about the Practitioner/Provider for the following purposes:
                <br></br>
                Publishing such information on the Website/Mobile Applications. Contacting Practitioners/Providers for offering new products or services. Contacting Practitioners/Providers for taking product feedback. Analyzing software usage patterns for improving product design and utility. Analyzing anonymized practice information including financial, and inventory information for commercial use.
                <br></br>
                3.2.4 Any personally identifiable information of the Providers listed on the Website/Mobile Applications is not generated by AIDFAST and is provided to AIDFAST by Practitioners/Providers who wish to enlist themselves on the Website/Mobile Applications, or is collected by AIDFAST from the public domain. AIDFAST displays such information on its Website/Mobile Applications on an as-is basis making no representation or warranty on the accuracy or completeness of the information. As such, we strongly encourage Practitioners/Providers to check the accuracy and completeness of their information from time to time, and inform us immediately of any discrepancies, changes, or updates to such information. AIDFAST will, however, take reasonable steps to ensure the accuracy and completeness of this information.
                <br></br>
                3.2.5 AIDFAST may also display information for Practitioners/Providers who have not signed up or registered for the services, provided that the Practitioners/Providers have consented to AIDFAST collecting, processing, and/or disclosing their information on the Website/Mobile Applications. Such Practitioners/Providers are verified by AIDFAST or its associates, and AIDFAST makes every effort to capture accurate information for such Practitioners/Providers. However, AIDFAST does not undertake any liability for any incorrect or incomplete information appearing on the Website for such Practitioners/Providers.
                <br></br>
                3.3 END-USERS NOTE:
                This section applies to all End-Users.
                <br></br>
                3.3.1 As part of the registration and submission process that is available to End-Users on this Website/Mobile Applications, certain information, including Personal Information or Sensitive Personal Data or Information is collected from the End-Users.
                <br></br>
                3.3.2 All the statements in this Privacy Policy apply to all End-Users, and all End-Users are therefore required to read and understand the privacy statements set out herein prior to submitting any Personal Information or Sensitive Personal Data or Information to AIDFAST , failing which they are required to leave the AIDFAST immediately.
                <br></br>
                3.3.3 End-Users personally identifiable information, which they choose to provide on the Website/Mobile Applications is used to help the End-Users describe/identify themselves. Other information that does not personally identify the End-Users as an individual, is collected by AIDFAST from End-Users (such as patterns of utilization described above) and is exclusively owned by AIDFAST. AIDFAST may also use such information in an aggregated or non-personally identifiable form for research, statistical analysis, and business intelligence purposes, and may sell or otherwise transfer such research, statistical, or intelligence data in an aggregated or non-personally identifiable form to third parties and affiliates. In particular, AIDFAST reserves with it the right to use anonymized End-User demographics information and anonymized End-User health information for the following purposes:
                <br></br>
                Analyzing software usage patterns for improving product design and utility. Analyzing such information for research and development of new technologies. Using analysis of such information in other commercial product offerings of AIDFAST. Sharing analysis of such information with third parties for commercial use.
                <br></br>
                3.3.4 AIDFAST will communicate with the End-Users through email, phone, or through other means, including text and other forms of messaging. The End-Users can change their e-mail and contact preferences at any time by logging in to their Account with AIDFAST.
                <br></br>
                3.3.5 AIDFAST may keep records of electronic communications and telephone calls received and made for making appointments or other purposes for the purpose of administration of services, customer support, research, and development.
                <br></br>
                3.3.6 All AIDFAST employees and data processors, who have access to, and are associated with the processing of sensitive personal data or information, are obliged to respect the confidentiality of every End-Users Personal Information or Sensitive Personal Data and Information. AIDFAST has put in place procedures and technologies as per good industry practices and in accordance with the applicable laws, to maintain the security of all personal data from the point of collection to the point of destruction. Any third-party data processor to which AIDFAST transfers personal data shall have to agree to comply with those procedures and policies, or put in place adequate measures on their own.
                <br></br>
                3.3.7 To the extent necessary to provide End-Users with the services, AIDFAST may provide their personal information to third-party contractors who work on behalf of or with AIDFAST to provide End-Users with such services, to help AIDFAST communicate with End-Users or to maintain the Website/Mobile Applications or independent third-party service providers to process payment instructions including providing a payment deferral facility to End-Users in relation to the services. These third-party service providers have access to information needed to process payments but may not use it for other purposes. Generally, these contractors do not have any independent right to share this information, however, certain contractors who provide services on the Website/Mobile Applications, including the providers of online communications services, may use and disclose the personal information collected in connection with the provision of these services in accordance with their own privacy policies. In such circumstances, you consent to us disclosing your Personal Iformation to contractors, solely for the intended purposes only.
                <br></br>
                3.4 CASUAL VISITORS NOTE:
                3.4.1 No sensitive personal data or information is automatically collected by AIDFAST from any casual visitors of this website/Mobile Application.
                <br></br>
                3.4.2 Nevertheless, certain provisions of this Privacy Policy are applicable to even such casual visitors, and such casual visitors are also required to read and understand the privacy statements set out herein, failing which they are required to leave this Website/Mobile Applications immediately.
                <br></br>
                3.4.3 If you, as a casual visitor, have inadvertently browsed any other page of this Website/Mobile Applications prior to reading the privacy statements set out herein, and you do not agree with the manner in which such information is obtained, collected, processed, stored, used, disclosed or retained, merely quitting this browser application should ordinarily clear all temporary cookies installed by AIDFAST. All visitors, however, are encouraged to use the â€œclear cookiesâ€ functionality of their browsers to ensure such clearing/deletion, as AIDFAST cannot guarantee, predict or provide for the behavior of the equipment of all the visitors of the Website/Mobile Applications.
                <br></br>
                3.4.4 You are not a casual visitor if you have willingly submitted any personal data or information to AIDFAST through any means, including email, post, or through the registration process on the Website/Mobile Applications. All such visitors will be deemed to be and will be treated as, Users for the purposes of this Privacy Policy, and in which case, all the statements in this Privacy Policy applies to such persons.
                <br></br>
                <b>4. CONFIDENTIALITY AND SECURITY</b>
                <br></br>
                4.1 Your personal information is maintained by AIDFAST in electronic form on its equipment, and on the equipment of its employees. Such information may also be converted to physical form from time to time. AIDFAST takes all necessary precautions to protect your personal information both online and off-line and implements reasonable security practices and measures including certain managerial, technical, operational, and physical security control measures that are commensurate with respect to the information being collected and the nature of aidfasts business.
                <br></br>
                4.2 No administrator at AIDFAST will have knowledge of your password. It is important for you to protect against unauthorized access to your password, your computer, and your mobile phone. Be sure to log off from the Website/Mobile Applications when finished. AIDFAST does not undertake any liability for any unauthorized use of your account and password. If you suspect any unauthorized use of your account, you must immediately notify AIDFAST by sending an email to contact@aidfastbd.com You shall be liable to indemnify AIDFAST due to any loss suffered by it due to such unauthorized use of your account and password.
                <br></br>
                4.3 AIDFAST makes all User information accessible to its employees, agents or partners, and third parties only on a need-to-know basis and binds only its employees to strict confidentiality obligations.
                <br></br>
                4.4 Part of the functionality of AIDFAST is assisting the doctors to maintain and organize such information. AIDFAST may, therefore, retain and submit all such records to the appropriate authorities, or to doctors who request access to such information.
                <br></br>
                4.5 Part of the functionality of AIDFAST is assisting the patients to access information relating to them. AIDFAST may, therefore, retain and submit all such records to the relevant patients, or to their doctors.
                <br></br>
                4.6 Notwithstanding the above, AIDFAST is not responsible for the confidentiality, security, or distribution of your personal information by our partners and third parties outside the scope of our agreement with such partners and third parties. Further, AIDFAST shall not be responsible for any breach of security or for any actions of any third parties or events that are beyond the reasonable control of AIDFAST including but not limited to, acts of government, computer hacking, unauthorized access to computer data, and storage device, computer crashes, breach of security and encryption, poor quality of Internet service or telephone service of the User, etc.
                <br></br>
                <b>5. CHANGE TO PRIVACY POLICY</b>
                <br></br>
                AIDFAST may update this Privacy Policy at any time, with or without advance notice. In the event, there are significant changes in the way AIDFAST treats Users personally identifiable information, or in the Privacy Policy itself, AIDFAST will display a notice on the Website/Mobile Applications or send Users an email, as provided above, so that you may review the changed terms prior to continuing to use the Services. As always, if you object to any of the changes to our terms, and you no longer wish to use the Services, you may contact contact@aidfastbd.com to deactivate your account. Unless stated otherwise, AIDFASTs current Privacy Policy applies to all information that AIDFAST has about you and your account. If a User uses the services or accesses the Website/Mobile Applications after a notice of changes has been sent to such User or published on the Website/Mobile Applications, such User hereby provides his/her/its consent to the changed terms.
                <br></br>
                <b>6. CHILDRENS AND MINORS PRIVACY</b>
                <br></br>
                AIDFAST strongly encourages parents and guardians to supervise the online activities of their minor children and consider using parental control tools available from online services and software manufacturers to help provide a child-friendly online environment. These tools also can prevent minors from disclosing their name, address, and other personally identifiable information online without parental permission. Although the AIDFAST Website/Mobile Applications and services are not intended for use by minors, AIDFAST respects the privacy of minors who may inadvertently use the internet or the mobile application.
                <br></br>
                <b>7. CONSENT TO THIS POLICYS</b>
                <br></br>

                You acknowledge that this Privacy Policy is a part of the Agreement of the Website/Mobile Applications and the other services, and you unconditionally agree that becoming a User of the Website/Mobile Applications and its services signifies your (i) assent to this Privacy Policy, and (ii) consent to AIDFAST using, collecting, processing and/or disclosing your personal information in the manner and for the purposes set out in this Privacy Policy. Your visit to the Website/Mobile Applications and use of the services is subject to this Privacy Policy and the Agreement.
            </div>
        </>
    )
}

export default page